#! /bin/bash
#to check file path existsor not
#Check file path editable or not

echo "Input file name"
read fname
if [ -e $fname ]
then
echo "file exist : " $fname
    if [ cat >> $fname ]
    then
    echo "file editable"
    else
    echo "file is not editable"
    fi

else
echo "file does not exist :" $fname
fi